#!/bin/bash

param=$1

export DO_TOKEN='{{ do_token }}'
IP='{{ floating_ip }}'
ID=$(curl -s http://169.254.169.254/metadata/v1/id)

if [ "start" == "$param" ] ; then
  python /usr/local/bin/assign-ip $IP $ID
  service minio start
  exit 0
elif [ "stop" == "$param" ] ; then
service minio stop
  exit 0;
elif [ "status" == "$param" ] ; then
  exit 0;
else
  echo "no such command $param"
  exit 1;
fi